<div class="navbar navbar-inverse navbar-static-top">
    <div class="container">
        <a href="#" class="navbar-brand">Blogger</a>

        <button class="navbar-toggle" data-toggle="collapse" data-target=".navHeaderCollapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>

        <div class="collapse navbar-collapse navHeaderCollapse">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="<?php echo $this->url('indexPost',array('action' => 'index')); ?>">Index</a></li>
                <li><a href="<?php echo $this->url('blogPost',array('action' => 'post'));?>">Blog</a></li>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown"  href="#">Dersler <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">PHP</a></li>
                        <li><a href="#">JavaScript</a></li>
                        <li><a href="#">HTML</a></li>
                        <li><a href="#">CSS</a></li>
                    </ul>
                </li>
                <li><a href="navbar.php">News</a></li>
                <li><a href="#contact" data-toggle="modal">Kontak</a></li>
                <li><a href="#">Impressum</a></li>
            </ul>
        </div>
    </div>
</div>
