<div class="container">
    <div class="row">
        <div class="span-12">
            <h1>Add New Customer</h1>
            <?php if(!empty($front_message)) :?>
                <div class="alert alert-<?php echo $front_message['type'] ?> alert-dismissable">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    <strong>Warning!</strong> <?php echo $front_message["message"] ?>
                </div>
            <?php endif; ?>

            <?php
            $form->setAttribute('action',$this->url("customersAdd",array("action" => "add")));
            $form->prepare();
            ?>

            <?php echo $this->form()->openTag($form)."\n";?>
                <?php echo  $this->formHidden($form->get('id')); ?>
                <table class="table table-striped table-bordered">
                    <tr>
                        <td>Gender</td>
                        <td><?php echo  $this->formRow($form->get('gender')); ?></td>
                    </tr>
                    <tr>
                        <td>Name</td>
                        <td><?php echo  $this->formRow($form->get('name')); ?></td>
                    </tr>
                    <tr>
                        <td>Email</td>
                        <td><?php echo  $this->formRow($form->get('email')); ?></td>
                    </tr>
                    <tr>
                        <td>Town</td>
                        <td><?php echo  $this->formRow($form->get('town')); ?></td>
                    </tr>
                    <tr>
                        <td></td>
                        <td><?php echo  $this->formSubmit($form->get('submit')); ?></td>
                    </tr>
                </table>
            <?php echo $this->form()->closeTag($form)."\n";?>
        </div>
    </div>
</div>