<div class="container">
    <div class="row">
        <div class="span-12">
            <a href="<?php echo $this->url('customersIndex',array('action' => 'index')); ?>" class="btn btn-default">
                <span class="glyphicon glyphicon-share-alt"></span>
                Go To Main Page
            </a>
            <br/><br/>
            <?php
            pa($this->customer,1)
            ?>
        </div>
    </div>
</div>