<div class="container">
    <div class="row">
        <div class="span-12">
            <?php
            // module/Album/view/album/album/add.phtml:
            $title = 'Add new album';
            $this->headTitle($title);
            ?>
            <h1><?php echo $this->escapeHtml($title); ?></h1>
            <?php
            $form->setAttribute('action', $this->url('albumAdd', array('action' => 'add')));
            $form->prepare();
            ?>
            <?php echo $this->form()->openTag($form);?>
            <?php echo $this->formHidden($form->get('id'));?>
                <table class="table  table-bordered table-striped">
                    <tr>
                        <td><?php echo $this->formRow($form->get('title'));?></td>
                    </tr>
                    <tr>
                        <td><?php echo $this->formRow($form->get('artist'));?></td>
                    </tr>
                    <tr>
                        <td><?php echo $this->formSubmit($form->get('submit'));?></td>
                    </tr>
                </table>
            <?php echo $this->form()->closeTag(); ?>
        </div>
    </div>
</div>