<?php
echo $this->menu;
?>
<div class="container">
    <div class="container">
        <div class="jumbotron text-center">
            <h1>Bootstrap Calismalarim</h1>
            <p>In this tutorial, we will be adding a jumbotron (formerly known as a hero unit) to our site. The purpose of the jumbotron is for large messages that you want your viewers to see clearly, such as your latest video or blog post.</p>
            <a href="#" class="btn btn-primary" id="popover-button" data-content="Burdada linkin icerigi konusunda bilgiler." data-original-title="Baslik">
                Harika Bir Özellik
            </a>
            <a href="#success" data-toggle="modal" class="btn btn-success">Basarildi!</a>
        </div>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <h3>Baslik 1</h3>
                <p>In this tutorial, we will be adding a jumbotron (formerly known as a hero unit) to our site. The purpose of the jumbotron is for large messages that you want your viewers to see clearly, such as your latest video or blog post.</p>
                <a href="#" class="btn btn-primary">Read More</a>
            </div>
            <div class="col-md-3">
                <h3>Baslik 2</h3>
                <p>In this tutorial, we will be adding a jumbotron (formerly known as a hero unit) to our site. The purpose of the jumbotron is for large messages that you want your viewers to see clearly, such as your latest video or blog post.</p>
                <a href="#" class="btn btn-primary">Read More</a>
            </div>
            <div class="col-md-3">
                <h3>Baslik 3</h3>
                <p>In this tutorial, we will be adding a jumbotron (formerly known as a hero unit) to our site. The purpose of the jumbotron is for large messages that you want your viewers to see clearly, such as your latest video or blog post.</p>
                <a href="#" class="btn btn-primary">Read More</a>
            </div>

            <div class="col-md-3">
                <h3>Baslik 4</h3>
                <p>In this tutorial, we will be adding a jumbotron (formerly known as a hero unit) to our site. The purpose of the jumbotron is for large messages that you want your viewers to see clearly, such as your latest video or blog post.</p>
                <a href="#" class="btn btn-primary">Read More</a>
            </div>
        </div>


        <div class="row">
            <div class="col-md-6">
                <div style="padding: 10px">
                    <h3>Content Hover. Resmin üstüne git!</h3>
                    <img id="d1" src="img/main.jpg" style="width: 100%;height: 250px"/>
                    <div class="contenthover">
                            <h4>Lorem ipsum dolor</h4>
                            <p>Pellentesque habitant morbi tristique senectus</p>
                            <p><a href="#" class="mybutton">Lorem ipsum</a></p>
                    </div>
                </div>
            </div>

            <div class="col-md-6">
                <h3>Twitter Standart Accordion</h3>
                <div class="panel-group" id="accordion2">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4 class="panel-title">
                                <a href="#first" data-toggle="collapse" data-parent="#accordion2">Bölüm 1</a>
                            </h4>
                        </div>
                        <div id="first" class="panel-collapse in collapse">
                            <div class="panel-body">
                                Lorem ipsum amet. Lorem ipsum amet.Lorem ipsum amet.
                            </div>
                        </div>
                    </div>

                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4 class="panel-title">
                                <a href="#second" data-toggle="collapse" data-parent="#accordion2">Bölüm 2</a>
                            </h4>
                        </div>
                        <div id="second" class="panel-collapse  collapse">
                            <div class="panel-body">
                                Lorem ipsum amet. Lorem ipsum amet.Lorem ipsum amet.
                            </div>
                        </div>
                    </div>

                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4 class="panel-title">
                                <a href="#third" data-toggle="collapse" data-parent="#accordion2">Bölüm 3</a>
                            </h4>
                        </div>
                        <div id="third" class="panel-collapse  collapse">
                            <div class="panel-body">
                                Lorem ipsum amet. Lorem ipsum amet.Lorem ipsum amet.
                            </div>
                        </div>
                    </div>

                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h4 class="panel-title">
                                <a href="#fourth" data-toggle="collapse" data-parent="accordion">Bölüm 4</a>
                            </h4>
                        </div>
                        <div id="fourth" class="panel-collapse  collapse">
                            <div class="panel-body">
                                Lorem ipsum amet. Lorem ipsum amet.Lorem ipsum amet.
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>

    <div class="navbar navbar-default navbar-fixed-bottom">
        <div class="container">
            <p class="navbar-text pull-left">Serdar Degirmenci Bootstrap Temasi</p>
            <a href="#" class="navbar-btn btn-danger btn pull-right">Youtube Videolari</a>
        </div>
    </div>

    <div id="contact" class="modal fade" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4>Bizimle Iletisime Gecin</h4>
                </div>
                <div class="modal-body">
                    <p>In this tutorial, we will be adding a jumbotron (formerly known as a hero unit) to our site. The purpose of the jumbotron is for large messages that you want your viewers to see clearly, such as your latest video or blog post.</p>
                </div>
                <div class="modal-footer">
                    <a href="#" class="btn btn-primary" data-dismiss="modal">Kapat</a>
                </div>
            </div>
        </div>
    </div>

    <div id="success" class="modal fade" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h2>Baslik</h2>
                </div>
                <div class="modal-body">
                    <p>In this tutorial, we will be adding a jumbotron (formerly known as a hero unit) to our site. The purpose of the jumbotron is for large messages that you want your viewers to see clearly, such as your latest video or blog post.</p>
                </div>
                <div class="modal-footer">
                    <span class="navbar-text pull-left">Serdar Degirmenci Yapti</span>
                    <a href="" class="btn btn-default navbar-btn pull-right" data-dismiss="modal">Kapat</a>
                </div>
            </div>
        </div>
    </div>
</div>