<?php
echo $this->menu;
?>
<div class="container">
    <div class="container">
        <div class="row">
            <div class="col-lg-9">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <div class="page-header">
                            <h3>Serdar Degirmenci
                                <small>Bugün 02.03.2014</small>
                            </h3>
                        </div>
                        <img src="img/lg.jpg" class="page-header-img" alt="Cok Yakinda Benim Olacan"/>

                        <p>In this tutorial, we will be adding a jumbotron (formerly known as a hero unit) to our site. The
                            purpose of the jumbotron is for large messages that you.</p>

                        <p>In this tutorial, we will be adding a jumbotron (formerly known as a hero unit) to our site. The
                            purpose of the jumbotron is for large messages that you.</p>

                        <p>In this tutorial, we will be adding a jumbotron (formerly known as a hero unit) to our site. The
                            purpose of the jumbotron is for large messages that you.</p>

                        <p>In this tutorial, we will be adding a jumbotron (formerly known as a hero unit) to our site. The
                            purpose of the jumbotron is for large messages that you.</p>

                        <p>In this tutorial, we will be adding a jumbotron (formerly known as a hero unit) to our site. The
                            purpose of the jumbotron is for large messages that you.</p>

                        <h3>Burda bir Baslik daha</h3>

                        <div class="row">
                            <div class="col-lg-3">
                                <h4>Baslik 1</h4>

                                <p>In this tutorial, we will be adding a jumbotron (formerly known as a hero unit) to our
                                    site. The purpose of the jumbotron is for large messages that you.</p>
                            </div>
                            <div class="col-lg-3">
                                <h4>Baslik 2</h4>

                                <p>In this tutorial, we will be adding a jumbotron (formerly known as a hero unit) to our
                                    site. The purpose of the jumbotron is for large messages that you.</p>
                            </div>
                            <div class="col-lg-3">
                                <h4>Baslik 3</h4>

                                <p>In this tutorial, we will be adding a jumbotron (formerly known as a hero unit) to our
                                    site. The purpose of the jumbotron is for large messages that you.</p>
                            </div>
                            <div class="col-lg-3">
                                <h4>Baslik 4</h4>

                                <p>In this tutorial, we will be adding a jumbotron (formerly known as a hero unit) to our
                                    site. The purpose of the jumbotron is for large messages that you.</p>
                            </div>
                        </div>


                        <div class="table-area col-lg-12">
                            <h2>Kullanici Listesi</h2>
                            <table class="table table-bordered table-striped">
                                <thead>
                                <tr>
                                    <th>Isim</th>
                                    <th>Email</th>
                                    <th>Yas</th>
                                </tr>
                                </thead>
                                <tbody>
                                <tr>
                                    <td>Serdar</td>
                                    <td>serdar@test.de</td>
                                    <td>28</td>
                                </tr>
                                <tr>
                                    <td>Ahmet</td>
                                    <td>ahmet@test.de</td>
                                    <td>23</td>
                                </tr>
                                <tr>
                                    <td>Mehmet</td>
                                    <td>mehmet@test.de</td>
                                    <td>25</td>
                                </tr>
                                <tr>
                                    <td>Mehmet</td>
                                    <td>mehmet@test.de</td>
                                    <td>25</td>
                                </tr>
                                <tr>
                                    <td>Mehmet</td>
                                    <td>mehmet@test.de</td>
                                    <td>25</td>
                                </tr>
                                <tr>
                                    <td>Mehmet</td>
                                    <td>mehmet@test.de</td>
                                    <td>25</td>
                                </tr>
                                </tbody>
                            </table>
                        </div>

                    </div>
                </div>
            </div>


            <div class="col-lg-3">
                <div class="list-group" id="blog-side-bar">
                    <a href="#" class="list-group-item active">
                        <h4 class="list-group-item-heading">Baslik</h4>

                        <p class="list-group-item-text">In this tutorial, we will be adding a jumbotron (formerly known as a
                            hero unit) to our site. The purpose of the jumbotron is for large messages that you.</p>
                    </a>
                    <a href="#" class="list-group-item">
                        <h4 class="list-group-item-heading">Baslik</h4>

                        <p class="list-group-item-text">In this tutorial, we will be adding a jumbotron (formerly known as a
                            hero unit) to our site. The purpose of the jumbotron is for large messages that you.</p>
                    </a>
                    <a href="#" class="list-group-item">
                        <h4 class="list-group-item-heading">Baslik</h4>

                        <p class="list-group-item-text">In this tutorial, we will be adding a jumbotron (formerly known as a
                            hero unit) to our site. The purpose of the jumbotron is for large messages that you.</p>
                    </a>
                    <a href="#" class="list-group-item">
                        <h4 class="list-group-item-heading">Baslik</h4>

                        <p class="list-group-item-text">In this tutorial, we will be adding a jumbotron (formerly known as a
                            hero unit) to our site. The purpose of the jumbotron is for large messages that you.</p>
                    </a>
                    <a href="#" class="list-group-item">
                        <h4 class="list-group-item-heading">Baslik</h4>

                        <p class="list-group-item-text">In this tutorial, we will be adding a jumbotron (formerly known as a
                            hero unit) to our site. The purpose of the jumbotron is for large messages that you.</p>
                    </a>
                </div>

                <div id="right-tabs">
                    <h4>Frameworks</h4>
                    <ul id="tabs" data-tabs="tabs" class="nav nav-tabs">
                        <li class="active"><a href="#zend" data-toggle="tab">Zend</a></li>
                        <li><a href="#symfony" data-toggle="tab">Symfony</a></li>
                        <li><a href="#kohana" data-toggle="tab">Kohana</a></li>
                    </ul>
                    <div id="my-tab-content" class="tab-content">
                        <div class="tab-pane active" id="zend">
                            <h3>Zend</h3>
                            <p>Zend hakkinda</p>
                        </div>
                        <div class="tab-pane" id="symfony">
                            <h3>Symfony</h3>
                            <p>Symfony hakkinda</p>
                        </div>
                        <div class="tab-pane" id="kohana">
                            <h3>Kohana</h3>
                            <p>Kohana hakkinda</p>
                        </div>
                    </div>
                </div>
                <hr/>
                <div id="right-tabs">
                    <h4>Languages</h4>
                    <ul id="my_tabs" class="nav nav-pills">
                        <li class="active"><a href="#php" data-toggle="tab">PHP</a></li>
                        <li><a href="#js" data-toggle="tab">JS</a></li>
                        <li><a href="#css" data-toggle="tab">CSS</a></li>
                        <li><a href="#html" data-toggle="tab">HTML</a></li>
                    </ul>
                    <div class="tab-content" id="my_tab_content">
                        <div id="php" class="tab-pane active">
                            <h3>PHP</h3>
                            <p>PHP hakkinda</p>
                        </div>
                        <div id="js" class="tab-pane">
                            <h3>JS</h3>
                            <p>JS hakkinda</p>
                        </div>
                        <div id="css" class="tab-pane">
                            <h3>CSS</h3>
                            <p>CSS hakkinda</p>
                        </div>
                        <div id="html" class="tab-pane">
                            <h3>HTML</h3>
                            <p>HTML hakkinda</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>