<div class="container">
    <div class="row">
        <div class="span-12">
            <?php
            $title = 'Delete task';
            $this->headTitle($title);
            ?>
            <h1><?php echo $this->escapeHtml($title); ?></h1>

            <p>Are you sure that you want to delete the
                '<?php echo $this->escapeHtml($task->getTitle()); ?>' task?
            </p>
            <?php
            $url = $this->url('task', array('action' => 'delete', 'id'=>$id)); ?>
            <form action="<?php echo $url; ?>" method="post">
                <div>
                    <input type="submit" class="btn btn-danger" name="del" value="Yes" />
                    <input type="submit" class="btn btn-primary" name="del" value="No" />
                </div>
            </form>
            </table>
        </div>
    </div>
</div>
