<div class="container">
    <div class="jumbotron text-center">
        <h1>Bootstrap Calismalarim</h1>
        <p>In this tutorial, we will be adding a jumbotron (formerly known as a hero unit) to our site. The purpose of the jumbotron is for large messages that you want your viewers to see clearly, such as your latest video or blog post.</p>
        <a href="#" class="btn btn-primary" id="popover-button" data-content="Burdada linkin icerigi konusunda bilgiler." data-original-title="Baslik">
            Harika Bir Özellik
        </a>
        <a href="#success" data-toggle="modal" class="btn btn-success">Basarildi!</a>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-md-3">
            <h3>Baslik 1</h3>
            <p>In this tutorial, we will be adding a jumbotron (formerly known as a hero unit) to our site. The purpose of the jumbotron is for large messages that you want your viewers to see clearly, such as your latest video or blog post.</p>
            <a href="#" class="btn btn-primary">Read More</a>
        </div>
        <div class="col-md-3">
            <h3>Baslik 2</h3>
            <p>In this tutorial, we will be adding a jumbotron (formerly known as a hero unit) to our site. The purpose of the jumbotron is for large messages that you want your viewers to see clearly, such as your latest video or blog post.</p>
            <a href="#" class="btn btn-primary">Read More</a>
        </div>
        <div class="col-md-3">
            <h3>Baslik 3</h3>
            <p>In this tutorial, we will be adding a jumbotron (formerly known as a hero unit) to our site. The purpose of the jumbotron is for large messages that you want your viewers to see clearly, such as your latest video or blog post.</p>
            <a href="#" class="btn btn-primary">Read More</a>
        </div>

        <div class="col-md-3">
            <h3>Baslik 4</h3>
            <p>In this tutorial, we will be adding a jumbotron (formerly known as a hero unit) to our site. The purpose of the jumbotron is for large messages that you want your viewers to see clearly, such as your latest video or blog post.</p>
            <a href="#" class="btn btn-primary">Read More</a>
        </div>
    </div>


    <div class="row">
        <div class="col-md-6">
            <div style="padding: 10px">
                <h3>Content Hover. Resmin üstüne git!</h3>
                <img id="d1" src="img/main.jpg" style="width: 100%;height: 250px"/>
                <div class="contenthover">
                        <h4>Lorem ipsum dolor</h4>
                        <p>Pellentesque habitant morbi tristique senectus</p>
                        <p><a href="#" class="mybutton">Lorem ipsum</a></p>
                </div>
            </div>
        </div>

        <div class="col-md-6">
            <h3>Twitter Standart Accordion</h3>
            <div class="panel-group" id="accordion2">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a href="#first" data-toggle="collapse" data-parent="#accordion2">Bölüm 1</a>
                        </h4>
                    </div>
                    <div id="first" class="panel-collapse in collapse">
                        <div class="panel-body">
                            Lorem ipsum amet. Lorem ipsum amet.Lorem ipsum amet.
                        </div>
                    </div>
                </div>

                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a href="#second" data-toggle="collapse" data-parent="#accordion2">Bölüm 2</a>
                        </h4>
                    </div>
                    <div id="second" class="panel-collapse  collapse">
                        <div class="panel-body">
                            Lorem ipsum amet. Lorem ipsum amet.Lorem ipsum amet.
                        </div>
                    </div>
                </div>

                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a href="#third" data-toggle="collapse" data-parent="#accordion2">Bölüm 3</a>
                        </h4>
                    </div>
                    <div id="third" class="panel-collapse  collapse">
                        <div class="panel-body">
                            Lorem ipsum amet. Lorem ipsum amet.Lorem ipsum amet.
                        </div>
                    </div>
                </div>

                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a href="#fourth" data-toggle="collapse" data-parent="accordion">Bölüm 4</a>
                        </h4>
                    </div>
                    <div id="fourth" class="panel-collapse  collapse">
                        <div class="panel-body">
                            Lorem ipsum amet. Lorem ipsum amet.Lorem ipsum amet.
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

<div class="navbar navbar-default navbar-fixed-bottom">
    <div class="container">
        <p class="navbar-text pull-left">Serdar Degirmenci Bootstrap Temasi</p>
        <a href="#" class="navbar-btn btn-danger btn pull-right">Youtube Videolari</a>
    </div>
</div>

<div id="contact" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4>Bizimle Iletisime Gecin</h4>
            </div>
            <div class="modal-body">
                <p>In this tutorial, we will be adding a jumbotron (formerly known as a hero unit) to our site. The purpose of the jumbotron is for large messages that you want your viewers to see clearly, such as your latest video or blog post.</p>
            </div>
            <div class="modal-footer">
                <a href="#" class="btn btn-primary" data-dismiss="modal">Kapat</a>
            </div>
        </div>
    </div>
</div>

<div id="success" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h2>Baslik</h2>
            </div>
            <div class="modal-body">
                <p>In this tutorial, we will be adding a jumbotron (formerly known as a hero unit) to our site. The purpose of the jumbotron is for large messages that you want your viewers to see clearly, such as your latest video or blog post.</p>
            </div>
            <div class="modal-footer">
                <span class="navbar-text pull-left">Serdar Degirmenci Yapti</span>
                <a href="" class="btn btn-default navbar-btn pull-right" data-dismiss="modal">Kapat</a>
            </div>
        </div>
    </div>
</div>






































<!--<div class="jumbotron">-->
<!--    <h1>--><?php //echo sprintf($this->translate('Welcome to %sZend Framework 2%s'), '<span class="zf-green">', '</span>') ?><!--</h1>-->
<!--    <p>--><?php //echo sprintf($this->translate('Congratulations! You have successfully installed the %sZF2 Skeleton Application%s. You are currently running Zend Framework version %s. This skeleton can serve as a simple starting point for you to begin building your application on ZF2.'), '<a href="https://github.com/zendframework/ZendSkeletonApplication" target="_blank">', '</a>', \Zend\Version\Version::VERSION) ?><!--</p>-->
<!--    <p><a class="btn btn-success btn-lg" href="https://github.com/zendframework/zf2" target="_blank">--><?php //echo $this->translate('Fork Zend Framework 2 on GitHub') ?><!-- &raquo;</a></p>-->
<!--</div>-->
<!---->
<!--<div class="row">-->
<!---->
<!--    <div class="col-md-4">-->
<!--        <div class="panel panel-default">-->
<!--            <div class="panel-heading">-->
<!--                <h3 class="panel-title">--><?php //echo $this->translate('Follow Development') ?><!--</h3>-->
<!--            </div>-->
<!--            <div class="panel-body">-->
<!--                <p>--><?php //echo sprintf($this->translate('Zend Framework 2 is under active development. If you are interested in following the development of ZF2, there is a special ZF2 portal on the official Zend Framework website which provides links to the ZF2 %swiki%s, %sdev blog%s, %sissue tracker%s, and much more. This is a great resource for staying up to date with the latest developments!'), '<a href="http://framework.zend.com/wiki/display/ZFDEV2/Home">', '</a>', '<a href="http://framework.zend.com/zf2/blog">', '</a>', '<a href="https://github.com/zendframework/zf2/issues">', '</a>') ?><!--</p>-->
<!--                <p><a class="btn btn-success pull-right" href="http://framework.zend.com/zf2" target="_blank">--><?php //echo $this->translate('ZF2 Development Portal') ?><!-- &raquo;</a></p>-->
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->
<!---->
<!--    <div class="col-md-4">-->
<!--        <div class="panel panel-default">-->
<!--            <div class="panel-heading">-->
<!--                <h3 class="panel-title">--><?php //echo $this->translate('Discover Modules') ?><!--</h3>-->
<!--            </div>-->
<!--            <div class="panel-body">-->
<!--                <p>--><?php //echo sprintf($this->translate('The community is working on developing a community site to serve as a repository and gallery for ZF2 modules. The project is available %son GitHub%s. The site is currently live and currently contains a list of some of the modules already available for ZF2.'), '<a href="https://github.com/zendframework/modules.zendframework.com">', '</a>') ?><!--</p>-->
<!--                <p><a class="btn btn-success pull-right" href="http://modules.zendframework.com/" target="_blank">--><?php //echo $this->translate('Explore ZF2 Modules') ?><!-- &raquo;</a></p>-->
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->
<!---->
<!--    <div class="col-md-4">-->
<!--        <div class="panel panel-default">-->
<!--            <div class="panel-heading">-->
<!--                <h3 class="panel-title">--><?php //echo $this->translate('Help &amp; Support') ?><!--</h3>-->
<!--            </div>-->
<!--            <div class="panel-body">-->
<!--                <p>--><?php //echo sprintf($this->translate('If you need any help or support while developing with ZF2, you may reach us via IRC: %s#zftalk on Freenode%s. We\'d love to hear any questions or feedback you may have regarding the beta releases. Alternatively, you may subscribe and post questions to the %smailing lists%s.'), '<a href="irc://irc.freenode.net/zftalk">', '</a>', '<a href="http://framework.zend.com/wiki/display/ZFDEV/Mailing+Lists">', '</a>') ?><!--</p>-->
<!--                <p><a class="btn btn-success pull-right" href="http://webchat.freenode.net?channels=zftalk" target="_blank">--><?php //echo $this->translate('Ping us on IRC') ?><!-- &raquo;</a></p>-->
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->
<!--</div>-->
